// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ScanMirrorRequest_Method int32

const (
	ScanMirrorRequest_ALL   ScanMirrorRequest_Method = 0
	ScanMirrorRequest_FTP   ScanMirrorRequest_Method = 1
	ScanMirrorRequest_RSYNC ScanMirrorRequest_Method = 2
)

var ScanMirrorRequest_Method_name = map[int32]string{
	0: "ALL",
	1: "FTP",
	2: "RSYNC",
}

var ScanMirrorRequest_Method_value = map[string]int32{
	"ALL":   0,
	"FTP":   1,
	"RSYNC": 2,
}

func (x ScanMirrorRequest_Method) String() string {
	return proto.EnumName(ScanMirrorRequest_Method_name, int32(x))
}

func (ScanMirrorRequest_Method) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{12, 0}
}

type VersionReply struct {
	Version              string   `protobuf:"bytes,1,opt,name=Version,proto3" json:"Version,omitempty"`
	Build                string   `protobuf:"bytes,2,opt,name=Build,proto3" json:"Build,omitempty"`
	GoVersion            string   `protobuf:"bytes,3,opt,name=GoVersion,proto3" json:"GoVersion,omitempty"`
	OS                   string   `protobuf:"bytes,4,opt,name=OS,proto3" json:"OS,omitempty"`
	Arch                 string   `protobuf:"bytes,5,opt,name=Arch,proto3" json:"Arch,omitempty"`
	GoMaxProcs           int32    `protobuf:"varint,6,opt,name=GoMaxProcs,proto3" json:"GoMaxProcs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionReply) Reset()         { *m = VersionReply{} }
func (m *VersionReply) String() string { return proto.CompactTextString(m) }
func (*VersionReply) ProtoMessage()    {}
func (*VersionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *VersionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionReply.Unmarshal(m, b)
}
func (m *VersionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionReply.Marshal(b, m, deterministic)
}
func (m *VersionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionReply.Merge(m, src)
}
func (m *VersionReply) XXX_Size() int {
	return xxx_messageInfo_VersionReply.Size(m)
}
func (m *VersionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionReply.DiscardUnknown(m)
}

var xxx_messageInfo_VersionReply proto.InternalMessageInfo

func (m *VersionReply) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *VersionReply) GetBuild() string {
	if m != nil {
		return m.Build
	}
	return ""
}

func (m *VersionReply) GetGoVersion() string {
	if m != nil {
		return m.GoVersion
	}
	return ""
}

func (m *VersionReply) GetOS() string {
	if m != nil {
		return m.OS
	}
	return ""
}

func (m *VersionReply) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

func (m *VersionReply) GetGoMaxProcs() int32 {
	if m != nil {
		return m.GoMaxProcs
	}
	return 0
}

type MatchRequest struct {
	Pattern              string   `protobuf:"bytes,1,opt,name=Pattern,proto3" json:"Pattern,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MatchRequest) Reset()         { *m = MatchRequest{} }
func (m *MatchRequest) String() string { return proto.CompactTextString(m) }
func (*MatchRequest) ProtoMessage()    {}
func (*MatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *MatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchRequest.Unmarshal(m, b)
}
func (m *MatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchRequest.Marshal(b, m, deterministic)
}
func (m *MatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchRequest.Merge(m, src)
}
func (m *MatchRequest) XXX_Size() int {
	return xxx_messageInfo_MatchRequest.Size(m)
}
func (m *MatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MatchRequest proto.InternalMessageInfo

func (m *MatchRequest) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

type Mirror struct {
	ID                   int32                `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	HttpURL              string               `protobuf:"bytes,3,opt,name=HttpURL,proto3" json:"HttpURL,omitempty"`
	RsyncURL             string               `protobuf:"bytes,4,opt,name=RsyncURL,proto3" json:"RsyncURL,omitempty"`
	FtpURL               string               `protobuf:"bytes,5,opt,name=FtpURL,proto3" json:"FtpURL,omitempty"`
	SponsorName          string               `protobuf:"bytes,6,opt,name=SponsorName,proto3" json:"SponsorName,omitempty"`
	SponsorURL           string               `protobuf:"bytes,7,opt,name=SponsorURL,proto3" json:"SponsorURL,omitempty"`
	SponsorLogoURL       string               `protobuf:"bytes,8,opt,name=SponsorLogoURL,proto3" json:"SponsorLogoURL,omitempty"`
	AdminName            string               `protobuf:"bytes,9,opt,name=AdminName,proto3" json:"AdminName,omitempty"`
	AdminEmail           string               `protobuf:"bytes,10,opt,name=AdminEmail,proto3" json:"AdminEmail,omitempty"`
	CustomData           string               `protobuf:"bytes,11,opt,name=CustomData,proto3" json:"CustomData,omitempty"`
	ContinentOnly        bool                 `protobuf:"varint,12,opt,name=ContinentOnly,proto3" json:"ContinentOnly,omitempty"`
	CountryOnly          bool                 `protobuf:"varint,13,opt,name=CountryOnly,proto3" json:"CountryOnly,omitempty"`
	ASOnly               bool                 `protobuf:"varint,14,opt,name=ASOnly,proto3" json:"ASOnly,omitempty"`
	Score                int32                `protobuf:"varint,15,opt,name=Score,proto3" json:"Score,omitempty"`
	Latitude             float32              `protobuf:"fixed32,16,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	Longitude            float32              `protobuf:"fixed32,17,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	ContinentCode        string               `protobuf:"bytes,18,opt,name=ContinentCode,proto3" json:"ContinentCode,omitempty"`
	CountryCodes         string               `protobuf:"bytes,19,opt,name=CountryCodes,proto3" json:"CountryCodes,omitempty"`
	ExcludedCountryCodes string               `protobuf:"bytes,20,opt,name=ExcludedCountryCodes,proto3" json:"ExcludedCountryCodes,omitempty"`
	Asnum                uint32               `protobuf:"varint,21,opt,name=Asnum,proto3" json:"Asnum,omitempty"`
	Comment              string               `protobuf:"bytes,22,opt,name=Comment,proto3" json:"Comment,omitempty"`
	Enabled              bool                 `protobuf:"varint,23,opt,name=Enabled,proto3" json:"Enabled,omitempty"`
	Up                   bool                 `protobuf:"varint,24,opt,name=Up,proto3" json:"Up,omitempty"`
	ExcludeReason        string               `protobuf:"bytes,25,opt,name=ExcludeReason,proto3" json:"ExcludeReason,omitempty"`
	StateSince           *timestamp.Timestamp `protobuf:"bytes,26,opt,name=StateSince,proto3" json:"StateSince,omitempty"`
	AllowRedirects       int32                `protobuf:"varint,27,opt,name=AllowRedirects,proto3" json:"AllowRedirects,omitempty"`
	LastSync             *timestamp.Timestamp `protobuf:"bytes,28,opt,name=LastSync,proto3" json:"LastSync,omitempty"`
	LastSuccessfulSync   *timestamp.Timestamp `protobuf:"bytes,29,opt,name=LastSuccessfulSync,proto3" json:"LastSuccessfulSync,omitempty"`
	LastModTime          *timestamp.Timestamp `protobuf:"bytes,30,opt,name=LastModTime,proto3" json:"LastModTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Mirror) Reset()         { *m = Mirror{} }
func (m *Mirror) String() string { return proto.CompactTextString(m) }
func (*Mirror) ProtoMessage()    {}
func (*Mirror) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{2}
}

func (m *Mirror) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mirror.Unmarshal(m, b)
}
func (m *Mirror) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mirror.Marshal(b, m, deterministic)
}
func (m *Mirror) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mirror.Merge(m, src)
}
func (m *Mirror) XXX_Size() int {
	return xxx_messageInfo_Mirror.Size(m)
}
func (m *Mirror) XXX_DiscardUnknown() {
	xxx_messageInfo_Mirror.DiscardUnknown(m)
}

var xxx_messageInfo_Mirror proto.InternalMessageInfo

func (m *Mirror) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Mirror) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Mirror) GetHttpURL() string {
	if m != nil {
		return m.HttpURL
	}
	return ""
}

func (m *Mirror) GetRsyncURL() string {
	if m != nil {
		return m.RsyncURL
	}
	return ""
}

func (m *Mirror) GetFtpURL() string {
	if m != nil {
		return m.FtpURL
	}
	return ""
}

func (m *Mirror) GetSponsorName() string {
	if m != nil {
		return m.SponsorName
	}
	return ""
}

func (m *Mirror) GetSponsorURL() string {
	if m != nil {
		return m.SponsorURL
	}
	return ""
}

func (m *Mirror) GetSponsorLogoURL() string {
	if m != nil {
		return m.SponsorLogoURL
	}
	return ""
}

func (m *Mirror) GetAdminName() string {
	if m != nil {
		return m.AdminName
	}
	return ""
}

func (m *Mirror) GetAdminEmail() string {
	if m != nil {
		return m.AdminEmail
	}
	return ""
}

func (m *Mirror) GetCustomData() string {
	if m != nil {
		return m.CustomData
	}
	return ""
}

func (m *Mirror) GetContinentOnly() bool {
	if m != nil {
		return m.ContinentOnly
	}
	return false
}

func (m *Mirror) GetCountryOnly() bool {
	if m != nil {
		return m.CountryOnly
	}
	return false
}

func (m *Mirror) GetASOnly() bool {
	if m != nil {
		return m.ASOnly
	}
	return false
}

func (m *Mirror) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *Mirror) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Mirror) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Mirror) GetContinentCode() string {
	if m != nil {
		return m.ContinentCode
	}
	return ""
}

func (m *Mirror) GetCountryCodes() string {
	if m != nil {
		return m.CountryCodes
	}
	return ""
}

func (m *Mirror) GetExcludedCountryCodes() string {
	if m != nil {
		return m.ExcludedCountryCodes
	}
	return ""
}

func (m *Mirror) GetAsnum() uint32 {
	if m != nil {
		return m.Asnum
	}
	return 0
}

func (m *Mirror) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *Mirror) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Mirror) GetUp() bool {
	if m != nil {
		return m.Up
	}
	return false
}

func (m *Mirror) GetExcludeReason() string {
	if m != nil {
		return m.ExcludeReason
	}
	return ""
}

func (m *Mirror) GetStateSince() *timestamp.Timestamp {
	if m != nil {
		return m.StateSince
	}
	return nil
}

func (m *Mirror) GetAllowRedirects() int32 {
	if m != nil {
		return m.AllowRedirects
	}
	return 0
}

func (m *Mirror) GetLastSync() *timestamp.Timestamp {
	if m != nil {
		return m.LastSync
	}
	return nil
}

func (m *Mirror) GetLastSuccessfulSync() *timestamp.Timestamp {
	if m != nil {
		return m.LastSuccessfulSync
	}
	return nil
}

func (m *Mirror) GetLastModTime() *timestamp.Timestamp {
	if m != nil {
		return m.LastModTime
	}
	return nil
}

type MirrorListReply struct {
	Mirrors              []*Mirror `protobuf:"bytes,1,rep,name=Mirrors,proto3" json:"Mirrors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MirrorListReply) Reset()         { *m = MirrorListReply{} }
func (m *MirrorListReply) String() string { return proto.CompactTextString(m) }
func (*MirrorListReply) ProtoMessage()    {}
func (*MirrorListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{3}
}

func (m *MirrorListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MirrorListReply.Unmarshal(m, b)
}
func (m *MirrorListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MirrorListReply.Marshal(b, m, deterministic)
}
func (m *MirrorListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MirrorListReply.Merge(m, src)
}
func (m *MirrorListReply) XXX_Size() int {
	return xxx_messageInfo_MirrorListReply.Size(m)
}
func (m *MirrorListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MirrorListReply.DiscardUnknown(m)
}

var xxx_messageInfo_MirrorListReply proto.InternalMessageInfo

func (m *MirrorListReply) GetMirrors() []*Mirror {
	if m != nil {
		return m.Mirrors
	}
	return nil
}

type MirrorID struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MirrorID) Reset()         { *m = MirrorID{} }
func (m *MirrorID) String() string { return proto.CompactTextString(m) }
func (*MirrorID) ProtoMessage()    {}
func (*MirrorID) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{4}
}

func (m *MirrorID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MirrorID.Unmarshal(m, b)
}
func (m *MirrorID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MirrorID.Marshal(b, m, deterministic)
}
func (m *MirrorID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MirrorID.Merge(m, src)
}
func (m *MirrorID) XXX_Size() int {
	return xxx_messageInfo_MirrorID.Size(m)
}
func (m *MirrorID) XXX_DiscardUnknown() {
	xxx_messageInfo_MirrorID.DiscardUnknown(m)
}

var xxx_messageInfo_MirrorID proto.InternalMessageInfo

func (m *MirrorID) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *MirrorID) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MatchReply struct {
	Mirrors              []*MirrorID `protobuf:"bytes,1,rep,name=Mirrors,proto3" json:"Mirrors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MatchReply) Reset()         { *m = MatchReply{} }
func (m *MatchReply) String() string { return proto.CompactTextString(m) }
func (*MatchReply) ProtoMessage()    {}
func (*MatchReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{5}
}

func (m *MatchReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchReply.Unmarshal(m, b)
}
func (m *MatchReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchReply.Marshal(b, m, deterministic)
}
func (m *MatchReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchReply.Merge(m, src)
}
func (m *MatchReply) XXX_Size() int {
	return xxx_messageInfo_MatchReply.Size(m)
}
func (m *MatchReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchReply.DiscardUnknown(m)
}

var xxx_messageInfo_MatchReply proto.InternalMessageInfo

func (m *MatchReply) GetMirrors() []*MirrorID {
	if m != nil {
		return m.Mirrors
	}
	return nil
}

type ChangeStatusRequest struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Enabled              bool     `protobuf:"varint,2,opt,name=Enabled,proto3" json:"Enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeStatusRequest) Reset()         { *m = ChangeStatusRequest{} }
func (m *ChangeStatusRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeStatusRequest) ProtoMessage()    {}
func (*ChangeStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{6}
}

func (m *ChangeStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeStatusRequest.Unmarshal(m, b)
}
func (m *ChangeStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeStatusRequest.Marshal(b, m, deterministic)
}
func (m *ChangeStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeStatusRequest.Merge(m, src)
}
func (m *ChangeStatusRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeStatusRequest.Size(m)
}
func (m *ChangeStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeStatusRequest proto.InternalMessageInfo

func (m *ChangeStatusRequest) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ChangeStatusRequest) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type MirrorIDRequest struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MirrorIDRequest) Reset()         { *m = MirrorIDRequest{} }
func (m *MirrorIDRequest) String() string { return proto.CompactTextString(m) }
func (*MirrorIDRequest) ProtoMessage()    {}
func (*MirrorIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{7}
}

func (m *MirrorIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MirrorIDRequest.Unmarshal(m, b)
}
func (m *MirrorIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MirrorIDRequest.Marshal(b, m, deterministic)
}
func (m *MirrorIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MirrorIDRequest.Merge(m, src)
}
func (m *MirrorIDRequest) XXX_Size() int {
	return xxx_messageInfo_MirrorIDRequest.Size(m)
}
func (m *MirrorIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MirrorIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MirrorIDRequest proto.InternalMessageInfo

func (m *MirrorIDRequest) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

type AddMirrorReply struct {
	Latitude             float32  `protobuf:"fixed32,1,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,2,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	Country              string   `protobuf:"bytes,3,opt,name=Country,proto3" json:"Country,omitempty"`
	Continent            string   `protobuf:"bytes,4,opt,name=Continent,proto3" json:"Continent,omitempty"`
	ASN                  string   `protobuf:"bytes,5,opt,name=ASN,proto3" json:"ASN,omitempty"`
	Warnings             []string `protobuf:"bytes,6,rep,name=Warnings,proto3" json:"Warnings,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddMirrorReply) Reset()         { *m = AddMirrorReply{} }
func (m *AddMirrorReply) String() string { return proto.CompactTextString(m) }
func (*AddMirrorReply) ProtoMessage()    {}
func (*AddMirrorReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{8}
}

func (m *AddMirrorReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMirrorReply.Unmarshal(m, b)
}
func (m *AddMirrorReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMirrorReply.Marshal(b, m, deterministic)
}
func (m *AddMirrorReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMirrorReply.Merge(m, src)
}
func (m *AddMirrorReply) XXX_Size() int {
	return xxx_messageInfo_AddMirrorReply.Size(m)
}
func (m *AddMirrorReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMirrorReply.DiscardUnknown(m)
}

var xxx_messageInfo_AddMirrorReply proto.InternalMessageInfo

func (m *AddMirrorReply) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *AddMirrorReply) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *AddMirrorReply) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *AddMirrorReply) GetContinent() string {
	if m != nil {
		return m.Continent
	}
	return ""
}

func (m *AddMirrorReply) GetASN() string {
	if m != nil {
		return m.ASN
	}
	return ""
}

func (m *AddMirrorReply) GetWarnings() []string {
	if m != nil {
		return m.Warnings
	}
	return nil
}

type UpdateMirrorReply struct {
	Diff                 string   `protobuf:"bytes,1,opt,name=Diff,proto3" json:"Diff,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMirrorReply) Reset()         { *m = UpdateMirrorReply{} }
func (m *UpdateMirrorReply) String() string { return proto.CompactTextString(m) }
func (*UpdateMirrorReply) ProtoMessage()    {}
func (*UpdateMirrorReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{9}
}

func (m *UpdateMirrorReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMirrorReply.Unmarshal(m, b)
}
func (m *UpdateMirrorReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMirrorReply.Marshal(b, m, deterministic)
}
func (m *UpdateMirrorReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMirrorReply.Merge(m, src)
}
func (m *UpdateMirrorReply) XXX_Size() int {
	return xxx_messageInfo_UpdateMirrorReply.Size(m)
}
func (m *UpdateMirrorReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMirrorReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMirrorReply proto.InternalMessageInfo

func (m *UpdateMirrorReply) GetDiff() string {
	if m != nil {
		return m.Diff
	}
	return ""
}

type GeoUpdateMirrorReply struct {
	Mirror               *Mirror  `protobuf:"bytes,1,opt,name=Mirror,proto3" json:"Mirror,omitempty"`
	Diff                 string   `protobuf:"bytes,2,opt,name=Diff,proto3" json:"Diff,omitempty"`
	Warnings             []string `protobuf:"bytes,3,rep,name=Warnings,proto3" json:"Warnings,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeoUpdateMirrorReply) Reset()         { *m = GeoUpdateMirrorReply{} }
func (m *GeoUpdateMirrorReply) String() string { return proto.CompactTextString(m) }
func (*GeoUpdateMirrorReply) ProtoMessage()    {}
func (*GeoUpdateMirrorReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{10}
}

func (m *GeoUpdateMirrorReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeoUpdateMirrorReply.Unmarshal(m, b)
}
func (m *GeoUpdateMirrorReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeoUpdateMirrorReply.Marshal(b, m, deterministic)
}
func (m *GeoUpdateMirrorReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeoUpdateMirrorReply.Merge(m, src)
}
func (m *GeoUpdateMirrorReply) XXX_Size() int {
	return xxx_messageInfo_GeoUpdateMirrorReply.Size(m)
}
func (m *GeoUpdateMirrorReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GeoUpdateMirrorReply.DiscardUnknown(m)
}

var xxx_messageInfo_GeoUpdateMirrorReply proto.InternalMessageInfo

func (m *GeoUpdateMirrorReply) GetMirror() *Mirror {
	if m != nil {
		return m.Mirror
	}
	return nil
}

func (m *GeoUpdateMirrorReply) GetDiff() string {
	if m != nil {
		return m.Diff
	}
	return ""
}

func (m *GeoUpdateMirrorReply) GetWarnings() []string {
	if m != nil {
		return m.Warnings
	}
	return nil
}

type RefreshRepositoryRequest struct {
	Rehash               bool     `protobuf:"varint,1,opt,name=Rehash,proto3" json:"Rehash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshRepositoryRequest) Reset()         { *m = RefreshRepositoryRequest{} }
func (m *RefreshRepositoryRequest) String() string { return proto.CompactTextString(m) }
func (*RefreshRepositoryRequest) ProtoMessage()    {}
func (*RefreshRepositoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{11}
}

func (m *RefreshRepositoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshRepositoryRequest.Unmarshal(m, b)
}
func (m *RefreshRepositoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshRepositoryRequest.Marshal(b, m, deterministic)
}
func (m *RefreshRepositoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshRepositoryRequest.Merge(m, src)
}
func (m *RefreshRepositoryRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshRepositoryRequest.Size(m)
}
func (m *RefreshRepositoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshRepositoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshRepositoryRequest proto.InternalMessageInfo

func (m *RefreshRepositoryRequest) GetRehash() bool {
	if m != nil {
		return m.Rehash
	}
	return false
}

type ScanMirrorRequest struct {
	ID                   int32                    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	AutoEnable           bool                     `protobuf:"varint,2,opt,name=AutoEnable,proto3" json:"AutoEnable,omitempty"`
	Protocol             ScanMirrorRequest_Method `protobuf:"varint,3,opt,name=Protocol,proto3,enum=ScanMirrorRequest_Method" json:"Protocol,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ScanMirrorRequest) Reset()         { *m = ScanMirrorRequest{} }
func (m *ScanMirrorRequest) String() string { return proto.CompactTextString(m) }
func (*ScanMirrorRequest) ProtoMessage()    {}
func (*ScanMirrorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{12}
}

func (m *ScanMirrorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanMirrorRequest.Unmarshal(m, b)
}
func (m *ScanMirrorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanMirrorRequest.Marshal(b, m, deterministic)
}
func (m *ScanMirrorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanMirrorRequest.Merge(m, src)
}
func (m *ScanMirrorRequest) XXX_Size() int {
	return xxx_messageInfo_ScanMirrorRequest.Size(m)
}
func (m *ScanMirrorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanMirrorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScanMirrorRequest proto.InternalMessageInfo

func (m *ScanMirrorRequest) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ScanMirrorRequest) GetAutoEnable() bool {
	if m != nil {
		return m.AutoEnable
	}
	return false
}

func (m *ScanMirrorRequest) GetProtocol() ScanMirrorRequest_Method {
	if m != nil {
		return m.Protocol
	}
	return ScanMirrorRequest_ALL
}

type ScanMirrorReply struct {
	Enabled              bool     `protobuf:"varint,1,opt,name=Enabled,proto3" json:"Enabled,omitempty"`
	FilesIndexed         int64    `protobuf:"varint,2,opt,name=FilesIndexed,proto3" json:"FilesIndexed,omitempty"`
	KnownIndexed         int64    `protobuf:"varint,3,opt,name=KnownIndexed,proto3" json:"KnownIndexed,omitempty"`
	Removed              int64    `protobuf:"varint,4,opt,name=Removed,proto3" json:"Removed,omitempty"`
	TZOffsetMs           int64    `protobuf:"varint,5,opt,name=TZOffsetMs,proto3" json:"TZOffsetMs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanMirrorReply) Reset()         { *m = ScanMirrorReply{} }
func (m *ScanMirrorReply) String() string { return proto.CompactTextString(m) }
func (*ScanMirrorReply) ProtoMessage()    {}
func (*ScanMirrorReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{13}
}

func (m *ScanMirrorReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanMirrorReply.Unmarshal(m, b)
}
func (m *ScanMirrorReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanMirrorReply.Marshal(b, m, deterministic)
}
func (m *ScanMirrorReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanMirrorReply.Merge(m, src)
}
func (m *ScanMirrorReply) XXX_Size() int {
	return xxx_messageInfo_ScanMirrorReply.Size(m)
}
func (m *ScanMirrorReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanMirrorReply.DiscardUnknown(m)
}

var xxx_messageInfo_ScanMirrorReply proto.InternalMessageInfo

func (m *ScanMirrorReply) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *ScanMirrorReply) GetFilesIndexed() int64 {
	if m != nil {
		return m.FilesIndexed
	}
	return 0
}

func (m *ScanMirrorReply) GetKnownIndexed() int64 {
	if m != nil {
		return m.KnownIndexed
	}
	return 0
}

func (m *ScanMirrorReply) GetRemoved() int64 {
	if m != nil {
		return m.Removed
	}
	return 0
}

func (m *ScanMirrorReply) GetTZOffsetMs() int64 {
	if m != nil {
		return m.TZOffsetMs
	}
	return 0
}

type StatsFileRequest struct {
	Pattern              string               `protobuf:"bytes,1,opt,name=Pattern,proto3" json:"Pattern,omitempty"`
	DateStart            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=DateStart,proto3" json:"DateStart,omitempty"`
	DateEnd              *timestamp.Timestamp `protobuf:"bytes,3,opt,name=DateEnd,proto3" json:"DateEnd,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *StatsFileRequest) Reset()         { *m = StatsFileRequest{} }
func (m *StatsFileRequest) String() string { return proto.CompactTextString(m) }
func (*StatsFileRequest) ProtoMessage()    {}
func (*StatsFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{14}
}

func (m *StatsFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatsFileRequest.Unmarshal(m, b)
}
func (m *StatsFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatsFileRequest.Marshal(b, m, deterministic)
}
func (m *StatsFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsFileRequest.Merge(m, src)
}
func (m *StatsFileRequest) XXX_Size() int {
	return xxx_messageInfo_StatsFileRequest.Size(m)
}
func (m *StatsFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatsFileRequest proto.InternalMessageInfo

func (m *StatsFileRequest) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

func (m *StatsFileRequest) GetDateStart() *timestamp.Timestamp {
	if m != nil {
		return m.DateStart
	}
	return nil
}

func (m *StatsFileRequest) GetDateEnd() *timestamp.Timestamp {
	if m != nil {
		return m.DateEnd
	}
	return nil
}

type StatsFileReply struct {
	Files                map[string]int64 `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *StatsFileReply) Reset()         { *m = StatsFileReply{} }
func (m *StatsFileReply) String() string { return proto.CompactTextString(m) }
func (*StatsFileReply) ProtoMessage()    {}
func (*StatsFileReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{15}
}

func (m *StatsFileReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatsFileReply.Unmarshal(m, b)
}
func (m *StatsFileReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatsFileReply.Marshal(b, m, deterministic)
}
func (m *StatsFileReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsFileReply.Merge(m, src)
}
func (m *StatsFileReply) XXX_Size() int {
	return xxx_messageInfo_StatsFileReply.Size(m)
}
func (m *StatsFileReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsFileReply.DiscardUnknown(m)
}

var xxx_messageInfo_StatsFileReply proto.InternalMessageInfo

func (m *StatsFileReply) GetFiles() map[string]int64 {
	if m != nil {
		return m.Files
	}
	return nil
}

type StatsMirrorRequest struct {
	ID                   int32                `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	DateStart            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=DateStart,proto3" json:"DateStart,omitempty"`
	DateEnd              *timestamp.Timestamp `protobuf:"bytes,3,opt,name=DateEnd,proto3" json:"DateEnd,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *StatsMirrorRequest) Reset()         { *m = StatsMirrorRequest{} }
func (m *StatsMirrorRequest) String() string { return proto.CompactTextString(m) }
func (*StatsMirrorRequest) ProtoMessage()    {}
func (*StatsMirrorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{16}
}

func (m *StatsMirrorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatsMirrorRequest.Unmarshal(m, b)
}
func (m *StatsMirrorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatsMirrorRequest.Marshal(b, m, deterministic)
}
func (m *StatsMirrorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsMirrorRequest.Merge(m, src)
}
func (m *StatsMirrorRequest) XXX_Size() int {
	return xxx_messageInfo_StatsMirrorRequest.Size(m)
}
func (m *StatsMirrorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsMirrorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatsMirrorRequest proto.InternalMessageInfo

func (m *StatsMirrorRequest) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *StatsMirrorRequest) GetDateStart() *timestamp.Timestamp {
	if m != nil {
		return m.DateStart
	}
	return nil
}

func (m *StatsMirrorRequest) GetDateEnd() *timestamp.Timestamp {
	if m != nil {
		return m.DateEnd
	}
	return nil
}

type StatsMirrorReply struct {
	Mirror               *Mirror  `protobuf:"bytes,1,opt,name=Mirror,proto3" json:"Mirror,omitempty"`
	Requests             int64    `protobuf:"varint,2,opt,name=Requests,proto3" json:"Requests,omitempty"`
	Bytes                int64    `protobuf:"varint,3,opt,name=Bytes,proto3" json:"Bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatsMirrorReply) Reset()         { *m = StatsMirrorReply{} }
func (m *StatsMirrorReply) String() string { return proto.CompactTextString(m) }
func (*StatsMirrorReply) ProtoMessage()    {}
func (*StatsMirrorReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{17}
}

func (m *StatsMirrorReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatsMirrorReply.Unmarshal(m, b)
}
func (m *StatsMirrorReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatsMirrorReply.Marshal(b, m, deterministic)
}
func (m *StatsMirrorReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsMirrorReply.Merge(m, src)
}
func (m *StatsMirrorReply) XXX_Size() int {
	return xxx_messageInfo_StatsMirrorReply.Size(m)
}
func (m *StatsMirrorReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsMirrorReply.DiscardUnknown(m)
}

var xxx_messageInfo_StatsMirrorReply proto.InternalMessageInfo

func (m *StatsMirrorReply) GetMirror() *Mirror {
	if m != nil {
		return m.Mirror
	}
	return nil
}

func (m *StatsMirrorReply) GetRequests() int64 {
	if m != nil {
		return m.Requests
	}
	return 0
}

func (m *StatsMirrorReply) GetBytes() int64 {
	if m != nil {
		return m.Bytes
	}
	return 0
}

type GetMirrorLogsRequest struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	MaxResults           int32    `protobuf:"varint,2,opt,name=MaxResults,proto3" json:"MaxResults,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMirrorLogsRequest) Reset()         { *m = GetMirrorLogsRequest{} }
func (m *GetMirrorLogsRequest) String() string { return proto.CompactTextString(m) }
func (*GetMirrorLogsRequest) ProtoMessage()    {}
func (*GetMirrorLogsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{18}
}

func (m *GetMirrorLogsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMirrorLogsRequest.Unmarshal(m, b)
}
func (m *GetMirrorLogsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMirrorLogsRequest.Marshal(b, m, deterministic)
}
func (m *GetMirrorLogsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMirrorLogsRequest.Merge(m, src)
}
func (m *GetMirrorLogsRequest) XXX_Size() int {
	return xxx_messageInfo_GetMirrorLogsRequest.Size(m)
}
func (m *GetMirrorLogsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMirrorLogsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMirrorLogsRequest proto.InternalMessageInfo

func (m *GetMirrorLogsRequest) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *GetMirrorLogsRequest) GetMaxResults() int32 {
	if m != nil {
		return m.MaxResults
	}
	return 0
}

type GetMirrorLogsReply struct {
	Line                 []string `protobuf:"bytes,1,rep,name=line,proto3" json:"line,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMirrorLogsReply) Reset()         { *m = GetMirrorLogsReply{} }
func (m *GetMirrorLogsReply) String() string { return proto.CompactTextString(m) }
func (*GetMirrorLogsReply) ProtoMessage()    {}
func (*GetMirrorLogsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{19}
}

func (m *GetMirrorLogsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMirrorLogsReply.Unmarshal(m, b)
}
func (m *GetMirrorLogsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMirrorLogsReply.Marshal(b, m, deterministic)
}
func (m *GetMirrorLogsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMirrorLogsReply.Merge(m, src)
}
func (m *GetMirrorLogsReply) XXX_Size() int {
	return xxx_messageInfo_GetMirrorLogsReply.Size(m)
}
func (m *GetMirrorLogsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMirrorLogsReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetMirrorLogsReply proto.InternalMessageInfo

func (m *GetMirrorLogsReply) GetLine() []string {
	if m != nil {
		return m.Line
	}
	return nil
}

type Metric struct {
	Filename             string   `protobuf:"bytes,1,opt,name=Filename,proto3" json:"Filename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metric) Reset()         { *m = Metric{} }
func (m *Metric) String() string { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()    {}
func (*Metric) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{20}
}

func (m *Metric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metric.Unmarshal(m, b)
}
func (m *Metric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metric.Marshal(b, m, deterministic)
}
func (m *Metric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metric.Merge(m, src)
}
func (m *Metric) XXX_Size() int {
	return xxx_messageInfo_Metric.Size(m)
}
func (m *Metric) XXX_DiscardUnknown() {
	xxx_messageInfo_Metric.DiscardUnknown(m)
}

var xxx_messageInfo_Metric proto.InternalMessageInfo

func (m *Metric) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

type MetricsList struct {
	Filename             []string `protobuf:"bytes,1,rep,name=Filename,proto3" json:"Filename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetricsList) Reset()         { *m = MetricsList{} }
func (m *MetricsList) String() string { return proto.CompactTextString(m) }
func (*MetricsList) ProtoMessage()    {}
func (*MetricsList) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{21}
}

func (m *MetricsList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricsList.Unmarshal(m, b)
}
func (m *MetricsList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricsList.Marshal(b, m, deterministic)
}
func (m *MetricsList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricsList.Merge(m, src)
}
func (m *MetricsList) XXX_Size() int {
	return xxx_messageInfo_MetricsList.Size(m)
}
func (m *MetricsList) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricsList.DiscardUnknown(m)
}

var xxx_messageInfo_MetricsList proto.InternalMessageInfo

func (m *MetricsList) GetFilename() []string {
	if m != nil {
		return m.Filename
	}
	return nil
}

type Status struct {
	Status               bool     `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{22}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterEnum("ScanMirrorRequest_Method", ScanMirrorRequest_Method_name, ScanMirrorRequest_Method_value)
	proto.RegisterType((*VersionReply)(nil), "VersionReply")
	proto.RegisterType((*MatchRequest)(nil), "MatchRequest")
	proto.RegisterType((*Mirror)(nil), "Mirror")
	proto.RegisterType((*MirrorListReply)(nil), "MirrorListReply")
	proto.RegisterType((*MirrorID)(nil), "MirrorID")
	proto.RegisterType((*MatchReply)(nil), "MatchReply")
	proto.RegisterType((*ChangeStatusRequest)(nil), "ChangeStatusRequest")
	proto.RegisterType((*MirrorIDRequest)(nil), "MirrorIDRequest")
	proto.RegisterType((*AddMirrorReply)(nil), "AddMirrorReply")
	proto.RegisterType((*UpdateMirrorReply)(nil), "UpdateMirrorReply")
	proto.RegisterType((*GeoUpdateMirrorReply)(nil), "GeoUpdateMirrorReply")
	proto.RegisterType((*RefreshRepositoryRequest)(nil), "RefreshRepositoryRequest")
	proto.RegisterType((*ScanMirrorRequest)(nil), "ScanMirrorRequest")
	proto.RegisterType((*ScanMirrorReply)(nil), "ScanMirrorReply")
	proto.RegisterType((*StatsFileRequest)(nil), "StatsFileRequest")
	proto.RegisterType((*StatsFileReply)(nil), "StatsFileReply")
	proto.RegisterMapType((map[string]int64)(nil), "StatsFileReply.FilesEntry")
	proto.RegisterType((*StatsMirrorRequest)(nil), "StatsMirrorRequest")
	proto.RegisterType((*StatsMirrorReply)(nil), "StatsMirrorReply")
	proto.RegisterType((*GetMirrorLogsRequest)(nil), "GetMirrorLogsRequest")
	proto.RegisterType((*GetMirrorLogsReply)(nil), "GetMirrorLogsReply")
	proto.RegisterType((*Metric)(nil), "Metric")
	proto.RegisterType((*MetricsList)(nil), "MetricsList")
	proto.RegisterType((*Status)(nil), "Status")
}

func init() {
	proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1)
}

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 1551 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0x5f, 0x6f, 0xdb, 0x46,
	0x12, 0x17, 0x25, 0x5b, 0xb2, 0x46, 0xb2, 0x2d, 0xaf, 0x1d, 0x1f, 0xa3, 0xe4, 0x12, 0x65, 0x2f,
	0x97, 0x28, 0x38, 0x1c, 0x73, 0xd1, 0x25, 0x77, 0x46, 0x2e, 0x77, 0x81, 0x4e, 0xb2, 0x1d, 0xb7,
	0x72, 0x6c, 0x50, 0x71, 0x8b, 0xf6, 0x8d, 0x11, 0x57, 0x32, 0x51, 0x8a, 0xab, 0x92, 0xab, 0xc4,
	0x02, 0xfa, 0x31, 0x8a, 0x3e, 0xf5, 0xa1, 0xfd, 0x00, 0x05, 0xfa, 0xe5, 0xfa, 0x5e, 0xcc, 0xee,
	0x52, 0xa2, 0x28, 0x5b, 0x4e, 0x53, 0xa0, 0x6f, 0x3b, 0xbf, 0x9d, 0xdd, 0x99, 0x9d, 0x3f, 0xbf,
	0x21, 0xa1, 0x18, 0x8e, 0x7a, 0xd6, 0x28, 0xe4, 0x82, 0x57, 0x6f, 0x0d, 0x38, 0x1f, 0xf8, 0xec,
	0xb1, 0x94, 0xde, 0x8e, 0xfb, 0x8f, 0xd9, 0x70, 0x24, 0x26, 0x7a, 0xf3, 0x6e, 0x7a, 0x53, 0x78,
	0x43, 0x16, 0x09, 0x67, 0x38, 0x52, 0x0a, 0xf4, 0x07, 0x03, 0xca, 0x9f, 0xb1, 0x30, 0xf2, 0x78,
	0x60, 0xb3, 0x91, 0x3f, 0x21, 0x26, 0x14, 0xb4, 0x6c, 0x1a, 0x35, 0xa3, 0x5e, 0xb4, 0x63, 0x91,
	0xec, 0xc0, 0xea, 0xff, 0xc7, 0x9e, 0xef, 0x9a, 0x59, 0x89, 0x2b, 0x81, 0xdc, 0x86, 0xe2, 0x21,
	0x8f, 0x4f, 0xe4, 0xe4, 0xce, 0x0c, 0x20, 0x1b, 0x90, 0x3d, 0xe9, 0x9a, 0x2b, 0x12, 0xce, 0x9e,
	0x74, 0x09, 0x81, 0x95, 0x66, 0xd8, 0x3b, 0x37, 0x57, 0x25, 0x22, 0xd7, 0xe4, 0x0e, 0xc0, 0x21,
	0x3f, 0x76, 0x2e, 0x4e, 0x43, 0xde, 0x8b, 0xcc, 0x7c, 0xcd, 0xa8, 0xaf, 0xda, 0x09, 0x84, 0xd6,
	0xa1, 0x7c, 0xec, 0x88, 0xde, 0xb9, 0xcd, 0xbe, 0x1e, 0xb3, 0x48, 0xa0, 0x87, 0xa7, 0x8e, 0x10,
	0x2c, 0x9c, 0x7a, 0xa8, 0x45, 0xfa, 0xdd, 0x1a, 0xe4, 0x8f, 0xbd, 0x30, 0xe4, 0x21, 0x1a, 0x3e,
	0x6a, 0xcb, 0xfd, 0x55, 0x3b, 0x7b, 0xd4, 0x46, 0xc3, 0xaf, 0x9d, 0x21, 0xd3, 0xbe, 0xcb, 0x35,
	0x5e, 0xf4, 0x4a, 0x88, 0xd1, 0x99, 0xdd, 0xd1, 0x8e, 0xc7, 0x22, 0xa9, 0xc2, 0x9a, 0x1d, 0x4d,
	0x82, 0x1e, 0x6e, 0x29, 0xe7, 0xa7, 0x32, 0xd9, 0x85, 0xfc, 0x81, 0x3a, 0xa4, 0x1e, 0xa1, 0x25,
	0x52, 0x83, 0x52, 0x77, 0xc4, 0x83, 0x88, 0x87, 0xd2, 0x50, 0x5e, 0x6e, 0x26, 0x21, 0x7c, 0xa8,
	0x16, 0xf1, 0x74, 0x41, 0x2a, 0x24, 0x10, 0xf2, 0x00, 0x36, 0xb4, 0xd4, 0xe1, 0x03, 0x8e, 0x3a,
	0x6b, 0x52, 0x27, 0x85, 0x62, 0xc8, 0x9b, 0xee, 0xd0, 0x0b, 0xa4, 0x9d, 0xa2, 0x0a, 0xf9, 0x14,
	0x40, 0x2b, 0x52, 0xd8, 0x1f, 0x3a, 0x9e, 0x6f, 0x82, 0xb2, 0x32, 0x43, 0x70, 0xbf, 0x35, 0x8e,
	0x04, 0x1f, 0xb6, 0x1d, 0xe1, 0x98, 0x25, 0xb5, 0x3f, 0x43, 0xc8, 0x7d, 0x58, 0x6f, 0xf1, 0x40,
	0x78, 0x01, 0x0b, 0xc4, 0x49, 0xe0, 0x4f, 0xcc, 0x72, 0xcd, 0xa8, 0xaf, 0xd9, 0xf3, 0x20, 0xbe,
	0xb6, 0xc5, 0xc7, 0x81, 0x08, 0x27, 0x52, 0x67, 0x5d, 0xea, 0x24, 0x21, 0x8c, 0x53, 0xb3, 0x2b,
	0x37, 0x37, 0xe4, 0xa6, 0x96, 0xb0, 0x8c, 0xba, 0x3d, 0x1e, 0x32, 0x73, 0x53, 0x26, 0x47, 0x09,
	0x18, 0xf1, 0x8e, 0x23, 0x3c, 0x31, 0x76, 0x99, 0x59, 0xa9, 0x19, 0xf5, 0xac, 0x3d, 0x95, 0xf1,
	0xbd, 0x1d, 0x1e, 0x0c, 0xd4, 0xe6, 0x96, 0xdc, 0x9c, 0x01, 0x73, 0xfe, 0xb6, 0xb8, 0xcb, 0x4c,
	0x22, 0x9f, 0x34, 0x0f, 0x12, 0x0a, 0x65, 0xed, 0x1c, 0x8a, 0x91, 0xb9, 0x2d, 0x95, 0xe6, 0x30,
	0xd2, 0x80, 0x9d, 0xfd, 0x8b, 0x9e, 0x3f, 0x76, 0x99, 0x3b, 0xa7, 0xbb, 0x23, 0x75, 0x2f, 0xdd,
	0xc3, 0xd7, 0x34, 0xa3, 0x60, 0x3c, 0x34, 0x6f, 0xd4, 0x8c, 0xfa, 0xba, 0xad, 0x04, 0xac, 0xac,
	0x16, 0x1f, 0x0e, 0x59, 0x20, 0xcc, 0x5d, 0x55, 0x59, 0x5a, 0xc4, 0x9d, 0xfd, 0xc0, 0x79, 0xeb,
	0x33, 0xd7, 0xfc, 0x93, 0x0c, 0x4b, 0x2c, 0x62, 0xc5, 0x9e, 0x8d, 0x4c, 0x53, 0x82, 0xd9, 0xb3,
	0x11, 0xbe, 0x4b, 0x5b, 0xb4, 0x99, 0x13, 0xf1, 0xc0, 0xbc, 0xa9, 0xde, 0x35, 0x07, 0x92, 0xe7,
	0x00, 0x5d, 0xe1, 0x08, 0xd6, 0xf5, 0x82, 0x1e, 0x33, 0xab, 0x35, 0xa3, 0x5e, 0x6a, 0x54, 0x2d,
	0xd5, 0xf5, 0x56, 0xdc, 0xf5, 0xd6, 0x9b, 0xb8, 0xeb, 0xed, 0x84, 0x36, 0xd6, 0x5b, 0xd3, 0xf7,
	0xf9, 0x7b, 0x9b, 0xb9, 0x5e, 0xc8, 0x7a, 0x22, 0x32, 0x6f, 0xc9, 0x94, 0xa4, 0x50, 0xf2, 0x2f,
	0xcc, 0x4d, 0x24, 0xba, 0x93, 0xa0, 0x67, 0xde, 0xbe, 0xd6, 0xc2, 0x54, 0x97, 0x7c, 0x02, 0x44,
	0xae, 0xc7, 0xbd, 0x1e, 0x8b, 0xa2, 0xfe, 0xd8, 0x97, 0x37, 0xfc, 0xf9, 0xda, 0x1b, 0x2e, 0x39,
	0x45, 0x5e, 0x40, 0x09, 0xd1, 0x63, 0xee, 0xa2, 0x9e, 0x79, 0xe7, 0xda, 0x4b, 0x92, 0xea, 0xf4,
	0x29, 0x6c, 0x2a, 0x5e, 0xe8, 0x78, 0x91, 0x50, 0x3c, 0x77, 0x0f, 0x0a, 0x0a, 0x8a, 0x4c, 0xa3,
	0x96, 0xab, 0x97, 0x1a, 0x05, 0x4b, 0xc9, 0x76, 0x8c, 0x53, 0x0b, 0xd6, 0xd4, 0xf2, 0xa8, 0xfd,
	0x21, 0x7c, 0x42, 0x9f, 0x00, 0x68, 0xa2, 0x42, 0x03, 0x7f, 0x49, 0x1b, 0x28, 0x5a, 0xf1, 0x6d,
	0x33, 0x13, 0x2f, 0x61, 0xbb, 0x75, 0xee, 0x04, 0x03, 0x86, 0x69, 0x19, 0x47, 0x31, 0xc5, 0xa5,
	0xad, 0x25, 0xaa, 0x26, 0x3b, 0x57, 0x35, 0xf4, 0x5e, 0xfc, 0xb2, 0xa3, 0xf6, 0x15, 0x87, 0xe9,
	0xcf, 0x06, 0x6c, 0x34, 0x5d, 0x57, 0xbf, 0x4e, 0xfa, 0x96, 0xec, 0x36, 0x63, 0x59, 0xb7, 0x65,
	0xd3, 0xdd, 0x26, 0x2b, 0x5b, 0xd6, 0x7f, 0xcc, 0x99, 0x5a, 0xc4, 0x73, 0xd3, 0x96, 0xd3, 0xa4,
	0x39, 0x03, 0x48, 0x05, 0x72, 0xcd, 0xee, 0x6b, 0x4d, 0x99, 0xb8, 0x44, 0x1f, 0x3e, 0x77, 0xc2,
	0xc0, 0x0b, 0x06, 0x48, 0xfa, 0x39, 0xe4, 0xd8, 0x58, 0xa6, 0x0f, 0x61, 0xeb, 0x6c, 0xe4, 0x3a,
	0x82, 0x25, 0x9d, 0x26, 0xb0, 0xd2, 0xf6, 0xfa, 0x7d, 0x4d, 0xfa, 0x72, 0x4d, 0x07, 0xb0, 0x73,
	0xc8, 0xf8, 0xa2, 0xee, 0xdd, 0x78, 0x10, 0x48, 0xed, 0x44, 0x72, 0xe3, 0xf9, 0x10, 0x5f, 0x96,
	0x9d, 0x5d, 0x36, 0xe7, 0x51, 0x2e, 0xe5, 0x51, 0x03, 0x4c, 0x9b, 0xf5, 0x43, 0x16, 0x61, 0x76,
	0x79, 0xe4, 0x09, 0x1e, 0x4e, 0xe2, 0x80, 0xef, 0x42, 0xde, 0x66, 0xe7, 0x4e, 0x74, 0x2e, 0x8d,
	0xad, 0xd9, 0x5a, 0xa2, 0x3f, 0x1a, 0xb0, 0xd5, 0xed, 0x39, 0x41, 0xec, 0xd8, 0xe5, 0xb9, 0x45,
	0xbe, 0x1e, 0x0b, 0xae, 0x12, 0xaa, 0xd3, 0x9b, 0x40, 0xc8, 0x33, 0x58, 0x3b, 0xc5, 0xf2, 0xee,
	0x71, 0x5f, 0x86, 0x7c, 0xa3, 0x71, 0xd3, 0x5a, 0xb8, 0xd5, 0x3a, 0x66, 0xe2, 0x9c, 0xbb, 0xf6,
	0x54, 0x95, 0xfe, 0x15, 0xf2, 0x0a, 0x23, 0x05, 0xc8, 0x35, 0x3b, 0x9d, 0x4a, 0x06, 0x17, 0x07,
	0x6f, 0x4e, 0x2b, 0x06, 0x29, 0xc2, 0xaa, 0xdd, 0xfd, 0xe2, 0x75, 0xab, 0x92, 0xa5, 0x3f, 0x19,
	0xb0, 0x99, 0xbc, 0x4d, 0x7f, 0x02, 0xc4, 0xd5, 0x66, 0xcc, 0x73, 0x14, 0x85, 0xf2, 0x81, 0xe7,
	0xb3, 0xe8, 0x28, 0x70, 0xd9, 0x85, 0x2e, 0xc6, 0x9c, 0x3d, 0x87, 0xa1, 0xce, 0xa7, 0x01, 0x7f,
	0x1f, 0xc4, 0x3a, 0x39, 0xa5, 0x93, 0xc4, 0xd0, 0x82, 0xcd, 0x86, 0xfc, 0x1d, 0x73, 0x65, 0xa5,
	0xe4, 0xec, 0x58, 0xc4, 0x68, 0xbc, 0xf9, 0xf2, 0xa4, 0xdf, 0x8f, 0x98, 0x38, 0x8e, 0x64, 0xb9,
	0xe4, 0xec, 0x04, 0x42, 0xbf, 0x37, 0xa0, 0x82, 0xbd, 0x12, 0xa1, 0xcd, 0x6b, 0xbf, 0x08, 0xc8,
	0x1e, 0x14, 0xdb, 0xc8, 0x77, 0xc2, 0x09, 0x85, 0xf4, 0x76, 0x39, 0x69, 0xcc, 0x94, 0xc9, 0x53,
	0x28, 0xa0, 0xb0, 0x1f, 0xa8, 0x17, 0x2c, 0x3f, 0x17, 0xab, 0xd2, 0x6f, 0x60, 0x23, 0xe1, 0x1d,
	0x06, 0xf3, 0x1f, 0xb0, 0xda, 0xc7, 0xf0, 0x68, 0x12, 0xa8, 0x5a, 0xf3, 0xfb, 0x96, 0x8c, 0xdd,
	0x3e, 0x76, 0x90, 0xad, 0x14, 0xab, 0x7b, 0x00, 0x33, 0x10, 0x1b, 0xe7, 0x2b, 0x36, 0xd1, 0xef,
	0xc2, 0x25, 0x8e, 0x9c, 0x77, 0x8e, 0x3f, 0x66, 0x3a, 0xfa, 0x4a, 0x78, 0x9e, 0xdd, 0x33, 0xe8,
	0xb7, 0x06, 0x10, 0x79, 0xfd, 0xf2, 0x8a, 0xfb, 0xa3, 0x83, 0xc2, 0x74, 0xca, 0x7e, 0x53, 0x83,
	0xe2, 0x27, 0x98, 0xf2, 0x3f, 0xd2, 0x0f, 0x9d, 0xca, 0xf2, 0x4b, 0x74, 0x22, 0x58, 0xa4, 0x6b,
	0x4b, 0x09, 0xf4, 0x00, 0xb9, 0x40, 0x68, 0x9e, 0xe7, 0x83, 0x68, 0x49, 0xc3, 0x1d, 0x3b, 0x17,
	0x36, 0x8b, 0xc6, 0xbe, 0xbe, 0x7b, 0xd5, 0x4e, 0x20, 0xb4, 0x0e, 0x24, 0x75, 0x8f, 0x66, 0x1f,
	0xdf, 0x0b, 0x98, 0x4c, 0x63, 0xd1, 0x96, 0x6b, 0x7a, 0x5f, 0xf6, 0x58, 0xe8, 0xf5, 0xd0, 0x5b,
	0xcc, 0x59, 0x80, 0x23, 0x41, 0xa5, 0x6a, 0x2a, 0xd3, 0x47, 0x50, 0x52, 0x5a, 0x11, 0x4e, 0x9f,
	0x94, 0x6a, 0x6e, 0x4e, 0xb5, 0x06, 0x79, 0x35, 0x08, 0x90, 0x53, 0xd4, 0x2a, 0xe6, 0x14, 0x25,
	0x35, 0x7e, 0x29, 0x42, 0xae, 0xd5, 0x39, 0x22, 0xcf, 0x00, 0x0e, 0x99, 0x88, 0x3f, 0xb3, 0x77,
	0x17, 0xd2, 0xb0, 0x8f, 0x3f, 0x01, 0xd5, 0x75, 0x2b, 0xf9, 0x6d, 0x4f, 0x33, 0xe4, 0x3f, 0x50,
	0x38, 0x1b, 0x0d, 0x42, 0xc7, 0x65, 0x57, 0x9e, 0xb9, 0x02, 0xa7, 0x19, 0xf2, 0x1c, 0x79, 0xce,
	0xe7, 0x8e, 0xfb, 0x11, 0x67, 0xff, 0x07, 0xe5, 0xe4, 0xa0, 0x23, 0x3b, 0xd6, 0x25, 0x73, 0x6f,
	0xc9, 0xf9, 0x06, 0xac, 0xc8, 0xe8, 0x5d, 0x65, 0xb9, 0x62, 0xa5, 0x06, 0x3c, 0xcd, 0x90, 0x47,
	0x00, 0x7a, 0x36, 0x06, 0x7d, 0x4e, 0x2a, 0x56, 0x6a, 0x50, 0x56, 0xe3, 0x9a, 0xa3, 0x19, 0xf2,
	0x10, 0x3f, 0xa9, 0xf5, 0x88, 0x24, 0x31, 0x5e, 0xdd, 0xb4, 0xe6, 0xe7, 0x26, 0xcd, 0x90, 0xbf,
	0x43, 0x39, 0x39, 0x6d, 0x66, 0xba, 0xc4, 0x5a, 0x98, 0x42, 0x32, 0x64, 0x65, 0xc5, 0x6c, 0x5a,
	0x7d, 0xd1, 0x89, 0xab, 0x9f, 0xfc, 0x02, 0x36, 0x53, 0xb3, 0xed, 0x92, 0xe3, 0x37, 0xac, 0xcb,
	0xe6, 0x1f, 0xcd, 0x90, 0x57, 0xb0, 0xb5, 0x30, 0xb0, 0xc8, 0x4d, 0xeb, 0xaa, 0x21, 0xb6, 0xc4,
	0x8f, 0xa7, 0x00, 0xb3, 0x09, 0x41, 0xc8, 0xe2, 0xf0, 0xa9, 0x56, 0xac, 0xd4, 0x08, 0xa1, 0x19,
	0xf2, 0x04, 0x8a, 0x53, 0xa6, 0x23, 0x5b, 0x56, 0x9a, 0xb3, 0xab, 0x9b, 0x29, 0x22, 0xa4, 0x19,
	0xf2, 0x6f, 0x28, 0x25, 0x78, 0x82, 0x6c, 0x5b, 0x8b, 0x5c, 0x56, 0xdd, 0xb2, 0xd2, 0x54, 0x42,
	0x33, 0x64, 0x0f, 0x56, 0x4e, 0xbd, 0x60, 0xf0, 0x11, 0x65, 0xf9, 0x5f, 0x58, 0x9f, 0xeb, 0x75,
	0x82, 0xf1, 0x5c, 0xe4, 0x90, 0xea, 0xb6, 0xb5, 0x48, 0x09, 0x34, 0x43, 0x2c, 0x55, 0x36, 0x8a,
	0x03, 0x0a, 0x96, 0x5a, 0x2c, 0x31, 0x67, 0x41, 0xb1, 0xcd, 0xfc, 0x0f, 0xd7, 0x7f, 0x00, 0x25,
	0x2c, 0x68, 0x4d, 0x1f, 0xb3, 0x13, 0x65, 0x2b, 0xc1, 0x28, 0xb2, 0xbb, 0x40, 0x8d, 0x68, 0xfc,
	0x6e, 0xf8, 0x88, 0x30, 0xbc, 0x84, 0x52, 0xdb, 0x8b, 0x7e, 0xc7, 0x05, 0x0d, 0x19, 0x47, 0xd5,
	0xcc, 0x4b, 0xaf, 0x28, 0x58, 0x4a, 0x89, 0x66, 0xc8, 0xdf, 0xa0, 0x24, 0x3f, 0x97, 0x75, 0xba,
	0xd7, 0xad, 0xe4, 0x5f, 0x7e, 0xb5, 0x64, 0xcd, 0xbe, 0xa5, 0x69, 0xe6, 0x6d, 0x5e, 0xde, 0xf3,
	0xcf, 0x5f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x30, 0xe6, 0x21, 0xd7, 0xf9, 0x10, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CLIClient is the client API for CLI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CLIClient interface {
	GetVersion(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionReply, error)
	Upgrade(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	Reload(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	ChangeStatus(ctx context.Context, in *ChangeStatusRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*MirrorListReply, error)
	MirrorInfo(ctx context.Context, in *MirrorIDRequest, opts ...grpc.CallOption) (*Mirror, error)
	AddMirror(ctx context.Context, in *Mirror, opts ...grpc.CallOption) (*AddMirrorReply, error)
	UpdateMirror(ctx context.Context, in *Mirror, opts ...grpc.CallOption) (*UpdateMirrorReply, error)
	RemoveMirror(ctx context.Context, in *MirrorIDRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GeoUpdateMirror(ctx context.Context, in *MirrorIDRequest, opts ...grpc.CallOption) (*GeoUpdateMirrorReply, error)
	RefreshRepository(ctx context.Context, in *RefreshRepositoryRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ScanMirror(ctx context.Context, in *ScanMirrorRequest, opts ...grpc.CallOption) (*ScanMirrorReply, error)
	StatsFile(ctx context.Context, in *StatsFileRequest, opts ...grpc.CallOption) (*StatsFileReply, error)
	StatsMirror(ctx context.Context, in *StatsMirrorRequest, opts ...grpc.CallOption) (*StatsMirrorReply, error)
	Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	GetMirrorLogs(ctx context.Context, in *GetMirrorLogsRequest, opts ...grpc.CallOption) (*GetMirrorLogsReply, error)
	AddMetric(ctx context.Context, in *Metric, opts ...grpc.CallOption) (*empty.Empty, error)
	DelMetric(ctx context.Context, in *Metric, opts ...grpc.CallOption) (*empty.Empty, error)
	ListMetrics(ctx context.Context, in *Metric, opts ...grpc.CallOption) (*MetricsList, error)
	EnableAuto(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	DisableAuto(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	GetStatusAuto(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Status, error)
	// Tools
	MatchMirror(ctx context.Context, in *MatchRequest, opts ...grpc.CallOption) (*MatchReply, error)
}

type cLIClient struct {
	cc grpc.ClientConnInterface
}

func NewCLIClient(cc grpc.ClientConnInterface) CLIClient {
	return &cLIClient{cc}
}

func (c *cLIClient) GetVersion(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionReply, error) {
	out := new(VersionReply)
	err := c.cc.Invoke(ctx, "/CLI/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) Upgrade(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/CLI/Upgrade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) Reload(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/CLI/Reload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) ChangeStatus(ctx context.Context, in *ChangeStatusRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/CLI/ChangeStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*MirrorListReply, error) {
	out := new(MirrorListReply)
	err := c.cc.Invoke(ctx, "/CLI/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) MirrorInfo(ctx context.Context, in *MirrorIDRequest, opts ...grpc.CallOption) (*Mirror, error) {
	out := new(Mirror)
	err := c.cc.Invoke(ctx, "/CLI/MirrorInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) AddMirror(ctx context.Context, in *Mirror, opts ...grpc.CallOption) (*AddMirrorReply, error) {
	out := new(AddMirrorReply)
	err := c.cc.Invoke(ctx, "/CLI/AddMirror", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) UpdateMirror(ctx context.Context, in *Mirror, opts ...grpc.CallOption) (*UpdateMirrorReply, error) {
	out := new(UpdateMirrorReply)
	err := c.cc.Invoke(ctx, "/CLI/UpdateMirror", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) RemoveMirror(ctx context.Context, in *MirrorIDRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/CLI/RemoveMirror", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) GeoUpdateMirror(ctx context.Context, in *MirrorIDRequest, opts ...grpc.CallOption) (*GeoUpdateMirrorReply, error) {
	out := new(GeoUpdateMirrorReply)
	err := c.cc.Invoke(ctx, "/CLI/GeoUpdateMirror", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) RefreshRepository(ctx context.Context, in *RefreshRepositoryRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/CLI/RefreshRepository", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) ScanMirror(ctx context.Context, in *ScanMirrorRequest, opts ...grpc.CallOption) (*ScanMirrorReply, error) {
	out := new(ScanMirrorReply)
	err := c.cc.Invoke(ctx, "/CLI/ScanMirror", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) StatsFile(ctx context.Context, in *StatsFileRequest, opts ...grpc.CallOption) (*StatsFileReply, error) {
	out := new(StatsFileReply)
	err := c.cc.Invoke(ctx, "/CLI/StatsFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) StatsMirror(ctx context.Context, in *StatsMirrorRequest, opts ...grpc.CallOption) (*StatsMirrorReply, error) {
	out := new(StatsMirrorReply)
	err := c.cc.Invoke(ctx, "/CLI/StatsMirror", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/CLI/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) GetMirrorLogs(ctx context.Context, in *GetMirrorLogsRequest, opts ...grpc.CallOption) (*GetMirrorLogsReply, error) {
	out := new(GetMirrorLogsReply)
	err := c.cc.Invoke(ctx, "/CLI/GetMirrorLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) AddMetric(ctx context.Context, in *Metric, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/CLI/AddMetric", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) DelMetric(ctx context.Context, in *Metric, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/CLI/DelMetric", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) ListMetrics(ctx context.Context, in *Metric, opts ...grpc.CallOption) (*MetricsList, error) {
	out := new(MetricsList)
	err := c.cc.Invoke(ctx, "/CLI/ListMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) EnableAuto(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/CLI/EnableAuto", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) DisableAuto(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/CLI/DisableAuto", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) GetStatusAuto(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/CLI/GetStatusAuto", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIClient) MatchMirror(ctx context.Context, in *MatchRequest, opts ...grpc.CallOption) (*MatchReply, error) {
	out := new(MatchReply)
	err := c.cc.Invoke(ctx, "/CLI/MatchMirror", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CLIServer is the server API for CLI service.
type CLIServer interface {
	GetVersion(context.Context, *empty.Empty) (*VersionReply, error)
	Upgrade(context.Context, *empty.Empty) (*empty.Empty, error)
	Reload(context.Context, *empty.Empty) (*empty.Empty, error)
	ChangeStatus(context.Context, *ChangeStatusRequest) (*empty.Empty, error)
	List(context.Context, *empty.Empty) (*MirrorListReply, error)
	MirrorInfo(context.Context, *MirrorIDRequest) (*Mirror, error)
	AddMirror(context.Context, *Mirror) (*AddMirrorReply, error)
	UpdateMirror(context.Context, *Mirror) (*UpdateMirrorReply, error)
	RemoveMirror(context.Context, *MirrorIDRequest) (*empty.Empty, error)
	GeoUpdateMirror(context.Context, *MirrorIDRequest) (*GeoUpdateMirrorReply, error)
	RefreshRepository(context.Context, *RefreshRepositoryRequest) (*empty.Empty, error)
	ScanMirror(context.Context, *ScanMirrorRequest) (*ScanMirrorReply, error)
	StatsFile(context.Context, *StatsFileRequest) (*StatsFileReply, error)
	StatsMirror(context.Context, *StatsMirrorRequest) (*StatsMirrorReply, error)
	Ping(context.Context, *empty.Empty) (*empty.Empty, error)
	GetMirrorLogs(context.Context, *GetMirrorLogsRequest) (*GetMirrorLogsReply, error)
	AddMetric(context.Context, *Metric) (*empty.Empty, error)
	DelMetric(context.Context, *Metric) (*empty.Empty, error)
	ListMetrics(context.Context, *Metric) (*MetricsList, error)
	EnableAuto(context.Context, *empty.Empty) (*empty.Empty, error)
	DisableAuto(context.Context, *empty.Empty) (*empty.Empty, error)
	GetStatusAuto(context.Context, *empty.Empty) (*Status, error)
	// Tools
	MatchMirror(context.Context, *MatchRequest) (*MatchReply, error)
}

// UnimplementedCLIServer can be embedded to have forward compatible implementations.
type UnimplementedCLIServer struct {
}

func (*UnimplementedCLIServer) GetVersion(ctx context.Context, req *empty.Empty) (*VersionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersion not implemented")
}
func (*UnimplementedCLIServer) Upgrade(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upgrade not implemented")
}
func (*UnimplementedCLIServer) Reload(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reload not implemented")
}
func (*UnimplementedCLIServer) ChangeStatus(ctx context.Context, req *ChangeStatusRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeStatus not implemented")
}
func (*UnimplementedCLIServer) List(ctx context.Context, req *empty.Empty) (*MirrorListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedCLIServer) MirrorInfo(ctx context.Context, req *MirrorIDRequest) (*Mirror, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MirrorInfo not implemented")
}
func (*UnimplementedCLIServer) AddMirror(ctx context.Context, req *Mirror) (*AddMirrorReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMirror not implemented")
}
func (*UnimplementedCLIServer) UpdateMirror(ctx context.Context, req *Mirror) (*UpdateMirrorReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMirror not implemented")
}
func (*UnimplementedCLIServer) RemoveMirror(ctx context.Context, req *MirrorIDRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveMirror not implemented")
}
func (*UnimplementedCLIServer) GeoUpdateMirror(ctx context.Context, req *MirrorIDRequest) (*GeoUpdateMirrorReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GeoUpdateMirror not implemented")
}
func (*UnimplementedCLIServer) RefreshRepository(ctx context.Context, req *RefreshRepositoryRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshRepository not implemented")
}
func (*UnimplementedCLIServer) ScanMirror(ctx context.Context, req *ScanMirrorRequest) (*ScanMirrorReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScanMirror not implemented")
}
func (*UnimplementedCLIServer) StatsFile(ctx context.Context, req *StatsFileRequest) (*StatsFileReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StatsFile not implemented")
}
func (*UnimplementedCLIServer) StatsMirror(ctx context.Context, req *StatsMirrorRequest) (*StatsMirrorReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StatsMirror not implemented")
}
func (*UnimplementedCLIServer) Ping(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedCLIServer) GetMirrorLogs(ctx context.Context, req *GetMirrorLogsRequest) (*GetMirrorLogsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMirrorLogs not implemented")
}
func (*UnimplementedCLIServer) AddMetric(ctx context.Context, req *Metric) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMetric not implemented")
}
func (*UnimplementedCLIServer) DelMetric(ctx context.Context, req *Metric) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelMetric not implemented")
}
func (*UnimplementedCLIServer) ListMetrics(ctx context.Context, req *Metric) (*MetricsList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMetrics not implemented")
}
func (*UnimplementedCLIServer) EnableAuto(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableAuto not implemented")
}
func (*UnimplementedCLIServer) DisableAuto(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableAuto not implemented")
}
func (*UnimplementedCLIServer) GetStatusAuto(ctx context.Context, req *empty.Empty) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatusAuto not implemented")
}
func (*UnimplementedCLIServer) MatchMirror(ctx context.Context, req *MatchRequest) (*MatchReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MatchMirror not implemented")
}

func RegisterCLIServer(s *grpc.Server, srv CLIServer) {
	s.RegisterService(&_CLI_serviceDesc, srv)
}

func _CLI_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CLI/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).GetVersion(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_Upgrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).Upgrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CLI/Upgrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).Upgrade(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_Reload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).Reload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CLI/Reload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).Reload(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_ChangeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).ChangeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CLI/ChangeStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).ChangeStatus(ctx, req.(*ChangeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CLI/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).List(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_MirrorInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MirrorIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).MirrorInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CLI/MirrorInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).MirrorInfo(ctx, req.(*MirrorIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_AddMirror_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Mirror)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).AddMirror(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CLI/AddMirror",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).AddMirror(ctx, req.(*Mirror))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_UpdateMirror_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Mirror)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).UpdateMirror(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CLI/UpdateMirror",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).UpdateMirror(ctx, req.(*Mirror))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_RemoveMirror_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MirrorIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).RemoveMirror(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CLI/RemoveMirror",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).RemoveMirror(ctx, req.(*MirrorIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_GeoUpdateMirror_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MirrorIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).GeoUpdateMirror(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CLI/GeoUpdateMirror",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).GeoUpdateMirror(ctx, req.(*MirrorIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_RefreshRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshRepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).RefreshRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CLI/RefreshRepository",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).RefreshRepository(ctx, req.(*RefreshRepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_ScanMirror_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanMirrorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).ScanMirror(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CLI/ScanMirror",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).ScanMirror(ctx, req.(*ScanMirrorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_StatsFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).StatsFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CLI/StatsFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).StatsFile(ctx, req.(*StatsFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_StatsMirror_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsMirrorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).StatsMirror(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CLI/StatsMirror",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).StatsMirror(ctx, req.(*StatsMirrorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CLI/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).Ping(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_GetMirrorLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMirrorLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).GetMirrorLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CLI/GetMirrorLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).GetMirrorLogs(ctx, req.(*GetMirrorLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_AddMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Metric)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).AddMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CLI/AddMetric",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).AddMetric(ctx, req.(*Metric))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_DelMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Metric)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).DelMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CLI/DelMetric",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).DelMetric(ctx, req.(*Metric))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_ListMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Metric)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).ListMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CLI/ListMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).ListMetrics(ctx, req.(*Metric))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_EnableAuto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).EnableAuto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CLI/EnableAuto",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).EnableAuto(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_DisableAuto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).DisableAuto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CLI/DisableAuto",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).DisableAuto(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_GetStatusAuto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).GetStatusAuto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CLI/GetStatusAuto",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).GetStatusAuto(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLI_MatchMirror_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServer).MatchMirror(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CLI/MatchMirror",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServer).MatchMirror(ctx, req.(*MatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CLI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CLI",
	HandlerType: (*CLIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _CLI_GetVersion_Handler,
		},
		{
			MethodName: "Upgrade",
			Handler:    _CLI_Upgrade_Handler,
		},
		{
			MethodName: "Reload",
			Handler:    _CLI_Reload_Handler,
		},
		{
			MethodName: "ChangeStatus",
			Handler:    _CLI_ChangeStatus_Handler,
		},
		{
			MethodName: "List",
			Handler:    _CLI_List_Handler,
		},
		{
			MethodName: "MirrorInfo",
			Handler:    _CLI_MirrorInfo_Handler,
		},
		{
			MethodName: "AddMirror",
			Handler:    _CLI_AddMirror_Handler,
		},
		{
			MethodName: "UpdateMirror",
			Handler:    _CLI_UpdateMirror_Handler,
		},
		{
			MethodName: "RemoveMirror",
			Handler:    _CLI_RemoveMirror_Handler,
		},
		{
			MethodName: "GeoUpdateMirror",
			Handler:    _CLI_GeoUpdateMirror_Handler,
		},
		{
			MethodName: "RefreshRepository",
			Handler:    _CLI_RefreshRepository_Handler,
		},
		{
			MethodName: "ScanMirror",
			Handler:    _CLI_ScanMirror_Handler,
		},
		{
			MethodName: "StatsFile",
			Handler:    _CLI_StatsFile_Handler,
		},
		{
			MethodName: "StatsMirror",
			Handler:    _CLI_StatsMirror_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _CLI_Ping_Handler,
		},
		{
			MethodName: "GetMirrorLogs",
			Handler:    _CLI_GetMirrorLogs_Handler,
		},
		{
			MethodName: "AddMetric",
			Handler:    _CLI_AddMetric_Handler,
		},
		{
			MethodName: "DelMetric",
			Handler:    _CLI_DelMetric_Handler,
		},
		{
			MethodName: "ListMetrics",
			Handler:    _CLI_ListMetrics_Handler,
		},
		{
			MethodName: "EnableAuto",
			Handler:    _CLI_EnableAuto_Handler,
		},
		{
			MethodName: "DisableAuto",
			Handler:    _CLI_DisableAuto_Handler,
		},
		{
			MethodName: "GetStatusAuto",
			Handler:    _CLI_GetStatusAuto_Handler,
		},
		{
			MethodName: "MatchMirror",
			Handler:    _CLI_MatchMirror_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
